# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2022 Google, Inc.
# Written by Andrew Scull <ascull@google.com>
#

obj-$(CONFIG_$(PHASE_)CMDLINE) += cmd_fuzz.o
obj-$(CONFIG_VIRTIO_SANDBOX) += virtio.o
obj-$(CONFIG_EFI_LOADER) += efi_load_image.o
obj-$(CONFIG_FIT) += fit_image_load.o
obj-y += image_decomp.o
obj-$(CONFIG_FS_BTRFS) += btrfs.o
obj-$(CONFIG_CMD_ELF) += elf_loader.o
obj-$(CONFIG_FS_EXT4) += ext4.o
